# .gitlab-ci.yml
# Root pipeline config importing automated validation and manual approval deployment gates

stages:
  - test
  - build
  - deploy_dev
  - deploy_prod

# Reusable Pipeline Config Imports
include:
  # 1. Automated pipelines triggered on push
  - local: '/cicd/gitlab-ci/automated-pipelines/lint-and-test.yml'
  - local: '/cicd/gitlab-ci/automated-pipelines/security-scans.yml'
  
  # 2. Manual pipelines triggered by approval clicks in the UI
  - local: '/cicd/gitlab-ci/manual-pipelines/infrastructure-apply.yml'
  - local: '/cicd/gitlab-ci/manual-pipelines/production-release.yml'

#---------------------------------------------------------
# GLOBAL VARIABLES
#---------------------------------------------------------
variables:
  CI_REGISTRY_IMAGE: "registry.gitlab.com/biswajitnanda223/senorita-outages"
  AZURE_CLIENT_ID: "00000000-0000-0000-0000-000000000000"
  AZURE_TENANT_ID: "00000000-0000-0000-0000-000000000000"
